/**
 * Compact but structurally complete fixtures mirroring the /api/v1 contract,
 * used by component and integration tests.
 */

import type {
  CompanyResearch,
  DiscoveryResponse,
  UniverseRankings,
} from "../api/types"

export const DISCOVERY: DiscoveryResponse = {
  count: 2,
  results: [
    {
      symbol: "TCS",
      company_name: "Tata Consultancy Services",
      sector: "information technology",
      research_available: true,
    },
    {
      symbol: "INFY",
      company_name: "Infosys",
      sector: "information technology",
      research_available: true,
    },
  ],
}

export const UNIVERSE: UniverseRankings = {
  as_of: "2026-08-10T12:00:00+00:00",
  horizon: "LONG_TERM",
  count: 2,
  point_in_time: {
    as_of: "2026-08-10T12:00:00+00:00",
    effective_as_of: "2026-08-10T12:00:00+00:00",
    market_as_of: "2026-08-07",
    evidence_included: 42,
    acquired_evidence_included: 14,
    future_evidence_excluded: 0,
    sources_discovered: 6,
    sources_accepted: 4,
    sources_rejected: 2,
    pit_checks_passed: true,
    notes: [],
  },
  results: [
    {
      symbol: "TCS",
      company_name: "Tata Consultancy Services",
      horizon: "LONG_TERM",
      score: "68.1",
      signal: "NEUTRAL",
      confidence: "81.1",
      coverage: "100",
      missing_components: [],
      components: { fundamentals: "77.5", risk: "90" },
    },
    {
      symbol: "INFY",
      company_name: "Infosys",
      horizon: "LONG_TERM",
      score: "60.0",
      signal: "NEUTRAL",
      confidence: "70.0",
      coverage: "82.4",
      missing_components: ["future_readiness"],
      components: { fundamentals: "70.0", risk: "80" },
    },
  ],
}

export const RESEARCH: CompanyResearch = {
  company: {
    symbol: "TCS",
    company_name: "Tata Consultancy Services",
    sector: "information technology",
    as_of: "2026-08-10T12:00:00+00:00",
  },
  assessment: {
    conclusion: "POSITIVE",
    confidence: "0.95",
    thesis: "TCS shows a predominantly positive research profile across the available evidence.",
    conflict_detected: true,
    direction: "MIXED",
    research_ready: true,
  },
  point_in_time: {
    as_of: "2026-08-10T12:00:00+00:00",
    effective_as_of: "2026-08-10T12:00:00+00:00",
    market_as_of: "2026-08-07",
    evidence_included: 3,
    acquired_evidence_included: 1,
    future_evidence_excluded: 0,
    sources_discovered: 6,
    sources_accepted: 4,
    sources_rejected: 2,
    pit_checks_passed: true,
    notes: [
      "No evidence in this response has an observation timestamp after the effective as_of.",
    ],
  },
  intelligence: {
    business_quality: {
      status: "SUPPORTED",
      confidence: "HIGH",
      observations: ["Broad-based demand and recurring revenue base."],
      unknown: [],
      positive_count: 1,
      negative_count: 0,
      source_ids: ["tcs-q1fy27-results"],
      provenance_ids: ["src-1"],
    },
    financial_quality: {
      status: "MIXED",
      confidence: "HIGH",
      observations: ["Revenue is reported.", "Net Profit is reported."],
      unknown: [],
      positive_count: 1,
      negative_count: 1,
      source_ids: [],
      provenance_ids: [],
    },
    transformation: null,
    capital_allocation: null,
    competitive_position: null,
    innovation: null,
    future_technology: null,
    customer_intelligence: null,
    management_intelligence: null,
    market_intelligence: null,
    risks_anomalies: {
      status: "UNKNOWN",
      confidence: "UNKNOWN",
      observations: [],
      unknown: ["No validated risk observations are available."],
      positive_count: 0,
      negative_count: 0,
      source_ids: [],
      provenance_ids: [],
    },
    unknown_missing: ["future technology"],
  },
  evidence: {
    positive: [
      {
        evidence_id: "ev-1",
        title: "Validated feature: revenue_growth",
        explanation: "Revenue growth is validated point-in-time evidence.",
        symbol: "TCS",
        evidence_type: "FEATURE",
        direction: "POSITIVE",
        confidence: "0.8",
        reliability: "VALIDATED",
        observation_at: "2026-08-10T12:00:00+00:00",
        source_ids: ["yahoo_finance_financials"],
        provenance_ids: ["p-1"],
      },
    ],
    negative: [
      {
        evidence_id: "ev-2",
        title: "Rising debt trend",
        explanation: "Total debt has risen across recent reporting periods.",
        symbol: "TCS",
        evidence_type: "TREND",
        direction: "NEGATIVE",
        confidence: "0.6",
        reliability: "VALIDATED",
        observation_at: "2026-08-10T12:00:00+00:00",
        source_ids: ["yahoo_finance_financials"],
        provenance_ids: ["p-1"],
      },
    ],
    neutral: [
      {
        evidence_id: "ev-3",
        title: "Source tcs-ai-partnerships contains relevant evidence.",
        explanation: "Context evidence retained without a directional bias.",
        symbol: "TCS",
        evidence_type: "SOURCE",
        direction: "NEUTRAL",
        confidence: "0.5",
        reliability: "ACQUIRED",
        observation_at: "2026-08-10T12:00:00+00:00",
        source_ids: ["tcs-ai-partnerships"],
        provenance_ids: ["p-2"],
      },
    ],
    conflict_detected: true,
    direction: "MIXED",
    positive_count: 1,
    negative_count: 1,
    neutral_count: 1,
    positive_weight: "1.0",
    negative_weight: "0.6",
    average_confidence: "0.7",
    weighted_confidence: "0.75",
  },
  narrative: {
    thesis: "TCS presents mixed evidence; competing evidence should be evaluated rather than reduced to a single directional conclusion.",
    supporting_evidence: ["Revenue growth is validated."],
    contradicting_evidence: ["Rising debt trend."],
    strongest_evidence: ["Revenue growth is validated."],
    uncertainty: ["AI-partnership pipeline is unquantified."],
    key_risks: ["Rising debt trend."],
    evidence_gaps: ["Future technology coverage is missing."],
    what_could_change_thesis: ["A material margin compression event."],
    has_conflict: true,
  },
  signals: [
    {
      signal_id: "TREND_REVENUE",
      category: "FINANCIAL_TREND",
      direction: "POSITIVE",
      severity: "INFO",
      confidence: "0.8",
      title: "Increasing revenue",
      explanation: "Revenue increased across 4 observations with consistent direction.",
      symbol: "TCS",
      observation_at: "2026-08-10T12:00:00+00:00",
      supporting_features: ["revenue"],
      supporting_metrics: [],
    },
    {
      signal_id: "TREND_DEBT",
      category: "FINANCIAL_TREND",
      direction: "NEGATIVE",
      severity: "WARNING",
      confidence: "0.6",
      title: "Rising total debt",
      explanation: "Total debt trend is negative across recent periods.",
      symbol: "TCS",
      observation_at: "2026-08-10T12:00:00+00:00",
      supporting_features: ["total_debt"],
      supporting_metrics: [],
    },
  ],
  data_quality: {
    market_validation_status: "NEEDS_REVIEW",
    market_accepted_records: 244,
    market_rejected_records: 0,
    financial_record_count: 4,
    financial_data_missing: false,
    feature_statuses: {
      revenue_growth: "VALID",
      cash_change: "MISSING",
    },
    context: {
      accepted_observations: 2,
      rejected_observations: 0,
      rejected_missing_availability: 0,
      rejected_not_known_at: 0,
    },
    provenance_completeness: {
      financial_records: true,
      market_source: true,
      financial_source: true,
      evidence_with_provenance: false,
    },
    warnings: ["some market records were rejected during ingestion"],
    provider_failures: [],
  },
  provenance: {
    market: {
      source: "yahoo_finance_market",
      dataset_id: "yahoo_finance_chart",
      record_id: "TCS_market_2026-08-10T12:00:00+00:00",
      retrieved_at: "2026-08-10T12:00:00+00:00",
      available_at: "2026-08-10T12:00:00+00:00",
    },
    financials: {
      source: "yahoo_finance_financials",
      dataset_id: "yahoo_finance_fundamentals",
      record_id: "TCS_financials_2026-08-10T12:00:00+00:00",
      retrieved_at: "2026-08-10T12:00:00+00:00",
      available_at: "2026-08-10T12:00:00+00:00",
    },
    archived_sources: ["tcs-q1fy27-results", "tcs-ai-partnerships"],
  },
  rankings: {
    intraday: {
      symbol: "TCS",
      company_name: "Tata Consultancy Services",
      horizon: "INTRADAY",
      score: "61.2",
      signal: "NEUTRAL",
      confidence: "70.0",
      coverage: "100",
      missing_components: [],
      components: { momentum: "61.2" },
    },
    swing: {
      symbol: "TCS",
      company_name: "Tata Consultancy Services",
      horizon: "SWING",
      score: "63.5",
      signal: "NEUTRAL",
      confidence: "72.0",
      coverage: "100",
      missing_components: [],
      components: { momentum: "63.5" },
    },
    long_term: {
      symbol: "TCS",
      company_name: "Tata Consultancy Services",
      horizon: "LONG_TERM",
      score: "68.1",
      signal: "NEUTRAL",
      confidence: "81.1",
      coverage: "77.1",
      missing_components: ["future_readiness", "ai_participation"],
      components: { fundamentals: "77.5", risk: "90" },
    },
  },
  research_score: {
    total: "66.9",
    signal: "NEUTRAL",
    confidence: "81.1",
    components: {
      fundamentals: "77.5",
      financial_trends: "38.3",
      cash_flow: "71.7",
      balance_sheet: "100",
      risk: "90",
      management: "50",
      market_behavior: "50",
      evidence_quality: "50",
    },
  },
}

export const DEGRADED_RESEARCH: CompanyResearch = {
  ...RESEARCH,
  point_in_time: {
    ...RESEARCH.point_in_time,
    pit_checks_passed: false,
  },
  data_quality: {
    ...RESEARCH.data_quality,
    provider_failures: ["missing-sources-provider"],
    financial_data_missing: true,
  },
}
