/**
 * Compact but structurally complete fixtures mirroring the /api/v1 contract,
 * used by component and integration tests.
 */

import type {
  CompanyResearch,
  DiscoveryResponse,
  UniverseRankings,
} from "../api/types"

export const DISCOVERY: DiscoveryResponse = {
  count: 2,
  results: [
    {
      symbol: "TCS",
      company_name: "Tata Consultancy Services",
      sector: "information technology",
      research_available: true,
    },
    {
      symbol: "INFY",
      company_name: "Infosys",
      sector: "information technology",
      research_available: true,
    },
  ],
}

export const UNIVERSE: UniverseRankings = {
  as_of: "2026-08-10T12:00:00+00:00",
  horizon: "LONG_TERM",
  count: 2,
  point_in_time: {
    as_of: "2026-08-10T12:00:00+00:00",
    effective_as_of: "2026-08-10T12:00:00+00:00",
    market_as_of: "2026-08-07",
    evidence_included: 42,
    acquired_evidence_included: 14,
    future_evidence_excluded: 0,
    sources_discovered: 6,
    sources_accepted: 4,
    sources_rejected: 2,
    pit_checks_passed: true,
    notes: [],
  },
  results: [
    {
      symbol: "TCS",
      company_name: "Tata Consultancy Services",
      horizon: "LONG_TERM",
      score: "68.1",
      signal: "NEUTRAL",
      confidence: "81.1",
      coverage: "100",
      missing_components: [],
      components: { fundamentals: "77.5", risk: "90" },
    },
    {
      symbol: "INFY",
      company_name: "Infosys",
      horizon: "LONG_TERM",
      score: "60.0",
      signal: "NEUTRAL",
      confidence: "70.0",
      coverage: "82.4",
      missing_components: ["future_readiness"],
      components: { fundamentals: "70.0", risk: "80" },
    },
  ],
}

export const RESEARCH: CompanyResearch = {
  company: {
    symbol: "TCS",
    company_name: "Tata Consultancy Services",
    sector: "information technology",
    as_of: "2026-08-10T12:00:00+00:00",
  },
  assessment: {
    conclusion: "POSITIVE",
    confidence: "0.95",
    thesis: "TCS shows a predominantly positive research profile across the available evidence.",
    conflict_detected: true,
    direction: "MIXED",
    research_ready: true,
  },
  point_in_time: {
    as_of: "2026-08-10T12:00:00+00:00",
    effective_as_of: "2026-08-10T12:00:00+00:00",
    market_as_of: "2026-08-07",
    evidence_included: 3,
    acquired_evidence_included: 1,
    future_evidence_excluded: 0,
    sources_discovered: 6,
    sources_accepted: 4,
    sources_rejected: 2,
    pit_checks_passed: true,
    notes: [
      "No evidence in this response has an observation timestamp after the effective as_of.",
    ],
  },
  intelligence: {
    business_quality: {
      status: "SUPPORTED",
      confidence: "HIGH",
      observations: ["Broad-based demand and recurring revenue base."],
      unknown: [],
      positive_count: 1,
      negative_count: 0,
      source_ids: ["tcs-q1fy27-results"],
      provenance_ids: ["src-1"],
    },
    financial_quality: {
      status: "MIXED",
      confidence: "HIGH",
      observations: ["Revenue is reported.", "Net Profit is reported."],
      unknown: [],
      positive_count: 1,
      negative_count: 1,
      source_ids: [],
      provenance_ids: [],
    },
    transformation: null,
    capital_allocation: null,
    competitive_position: null,
    innovation: null,
    future_technology: null,
    customer_intelligence: null,
    management_intelligence: null,
    market_intelligence: null,
    risks_anomalies: {
      status: "UNKNOWN",
      confidence: "UNKNOWN",
      observations: [],
      unknown: ["No validated risk observations are available."],
      positive_count: 0,
      negative_count: 0,
      source_ids: [],
      provenance_ids: [],
    },
    unknown_missing: ["future technology"],
  },
  evidence: {
    positive: [
      {
        evidence_id: "ev-1",
        title: "Validated feature: revenue_growth",
        explanation: "Revenue growth is validated point-in-time evidence.",
        symbol: "TCS",
        evidence_type: "FEATURE",
        direction: "POSITIVE",
        confidence: "0.8",
        reliability: "VALIDATED",
        observation_at: "2026-08-10T12:00:00+00:00",
        source_ids: ["yahoo_finance_financials"],
        provenance_ids: ["p-1"],
      },
    ],
    negative: [
      {
        evidence_id: "ev-2",
        title: "Rising debt trend",
        explanation: "Total debt has risen across recent reporting periods.",
        symbol: "TCS",
        evidence_type: "TREND",
        direction: "NEGATIVE",
        confidence: "0.6",
        reliability: "VALIDATED",
        observation_at: "2026-08-10T12:00:00+00:00",
        source_ids: ["yahoo_finance_financials"],
        provenance_ids: ["p-1"],
      },
    ],
    neutral: [
      {
        evidence_id: "ev-3",
        title: "Source tcs-ai-partnerships contains relevant evidence.",
        explanation: "Context evidence retained without a directional bias.",
        symbol: "TCS",
        evidence_type: "SOURCE",
        direction: "NEUTRAL",
        confidence: "0.5",
        reliability: "ACQUIRED",
        observation_at: "2026-08-10T12:00:00+00:00",
        source_ids: ["tcs-ai-partnerships"],
        provenance_ids: ["p-2"],
      },
    ],
    conflict_detected: true,
    direction: "MIXED",
    positive_count: 1,
    negative_count: 1,
    neutral_count: 1,
    positive_weight: "1.0",
    negative_weight: "0.6",
    average_confidence: "0.7",
    weighted_confidence: "0.75",
  },
  narrative: {
    thesis: "TCS presents mixed evidence; competing evidence should be evaluated rather than reduced to a single directional conclusion.",
    supporting_evidence: ["Revenue growth is validated."],
    contradicting_evidence: ["Rising debt trend."],
    strongest_evidence: ["Revenue growth is validated."],
    uncertainty: ["AI-partnership pipeline is unquantified."],
    key_risks: ["Rising debt trend."],
    evidence_gaps: ["Future technology coverage is missing."],
    what_could_change_thesis: ["A material margin compression event."],
    has_conflict: true,
  },
  signals: [
    {
      signal_id: "TREND_REVENUE",
      category: "FINANCIAL_TREND",
      direction: "POSITIVE",
      severity: "INFO",
      confidence: "0.8",
      title: "Increasing revenue",
      explanation: "Revenue increased across 4 observations with consistent direction.",
      symbol: "TCS",
      observation_at: "2026-08-10T12:00:00+00:00",
      supporting_features: ["revenue"],
      supporting_metrics: [],
    },
    {
      signal_id: "TREND_DEBT",
      category: "FINANCIAL_TREND",
      direction: "NEGATIVE",
      severity: "WARNING",
      confidence: "0.6",
      title: "Rising total debt",
      explanation: "Total debt trend is negative across recent periods.",
      symbol: "TCS",
      observation_at: "2026-08-10T12:00:00+00:00",
      supporting_features: ["total_debt"],
      supporting_metrics: [],
    },
  ],
  data_quality: {
    market_validation_status: "NEEDS_REVIEW",
    market_accepted_records: 244,
    market_rejected_records: 0,
    financial_record_count: 4,
    financial_data_missing: false,
    feature_statuses: {
      revenue_growth: "VALID",
      cash_change: "MISSING",
    },
    context: {
      accepted_observations: 2,
      rejected_observations: 0,
      rejected_missing_availability: 0,
      rejected_not_known_at: 0,
    },
    provenance_completeness: {
      financial_records: true,
      market_source: true,
      financial_source: true,
      evidence_with_provenance: false,
    },
    warnings: ["some market records were rejected during ingestion"],
    provider_failures: [],
  },
  provenance: {
    market: {
      source: "yahoo_finance_market",
      dataset_id: "yahoo_finance_chart",
      record_id: "TCS_market_2026-08-10T12:00:00+00:00",
      retrieved_at: "2026-08-10T12:00:00+00:00",
      available_at: "2026-08-10T12:00:00+00:00",
    },
    financials: {
      source: "yahoo_finance_financials",
      dataset_id: "yahoo_finance_fundamentals",
      record_id: "TCS_financials_2026-08-10T12:00:00+00:00",
      retrieved_at: "2026-08-10T12:00:00+00:00",
      available_at: "2026-08-10T12:00:00+00:00",
    },
    archived_sources: ["tcs-q1fy27-results", "tcs-ai-partnerships"],
  },
  timeline: {
    company: "TCS",
    as_of: "2026-08-10T12:00:00+00:00",
    entries: [
      {
        entry_id: "timeline:TCS:board-meeting-june",
        symbol: "TCS",
        kind: "BUSINESS_EVENT",
        intel_category: "CORPORATE_ACTION",
        semantic_category: "FACT",
        verification_status: "CONFIRMED",
        event_type: "BOARD_MEETING",
        topic: "governance",
        title: "TCS board meeting scheduled for June",
        description: "The board meeting was disclosed and recorded.",
        stance: "NEUTRAL",
        direction: "UNKNOWN",
        published_at: "2026-06-22T18:30:00+00:00",
        available_at: "2026-06-22T18:30:00+00:00",
        effective_at: null,
        timeline_at: "2026-06-22T18:30:00+00:00",
        source: {
          source_name: "recorded_intel_sources",
          source_type: "COMPANY_DISCLOSURES",
          source_url: "https://example.invalid/board-june",
          reliability_tier: 2,
          provenance_id: "intel-1",
        },
        provenance_id: "intel-1",
        checksum: "checksum-board",
      },
      {
        entry_id: "timeline:TCS:fy27-results",
        symbol: "TCS",
        kind: "FINANCIAL_PERIOD",
        semantic_category: "FACT",
        verification_status: "CONFIRMED",
        event_type: null,
        topic: "financial_reporting",
        title: "TCS ANNUAL financials for the period ending 2026-03-31",
        description:
          "Reported revenue 279331000000.0 and reported net profit 44019000000.0.",
        stance: "NEUTRAL",
        direction: "NEUTRAL",
        intel_category: "FINANCIAL_DISCLOSURE",
        published_at: "2026-07-09T18:30:00+00:00",
        available_at: "2026-08-10T12:00:00+00:00",
        effective_at: null,
        timeline_at: "2026-07-09T18:30:00+00:00",
        source: {
          source_name: "recorded_financials",
          source_type: "COMPANY_FILINGS",
          source_url: "https://example.invalid/fy27",
          reliability_tier: 1,
          provenance_id: "fin-1",
        },
        provenance_id: "fin-1",
        checksum: "checksum-fy27",
      },
      {
        entry_id: "timeline:TCS:dividend",
        symbol: "TCS",
        kind: "BUSINESS_EVENT",
        intel_category: "CORPORATE_ACTION",
        semantic_category: "FACT",
        verification_status: "CONFIRMED",
        event_type: "DIVIDEND",
        topic: "dividends",
        title: "TCS declares a dividend",
        description: "A dividend declaration was disclosed.",
        stance: "SUPPORTIVE",
        direction: "NEUTRAL",
        published_at: "2026-07-09T19:00:00+00:00",
        available_at: "2026-07-09T19:00:00+00:00",
        effective_at: null,
        timeline_at: "2026-07-09T19:00:00+00:00",
        source: {
          source_name: "recorded_intel_sources",
          source_type: "COMPANY_DISCLOSURES",
          source_url: "https://example.invalid/dividend",
          reliability_tier: 2,
          provenance_id: "intel-2",
        },
        provenance_id: "intel-2",
        checksum: "checksum-dividend",
      },
      {
        entry_id: "timeline:TCS:management-commentary",
        symbol: "TCS",
        kind: "MANAGEMENT_COMMENTARY",
        intel_category: "MANAGEMENT_STATEMENT",
        semantic_category: "MANAGEMENT_COMMENTARY",
        verification_status: "REPORTED",
        event_type: null,
        topic: "management",
        title: "TCS management guidance on AI adoption",
        description:
          "Management statements on AI adoption were recorded.",
        stance: "SUPPORTIVE",
        direction: "POSITIVE",
        published_at: "2026-07-30T12:00:00+00:00",
        available_at: "2026-07-30T12:00:00+00:00",
        effective_at: null,
        timeline_at: "2026-07-30T12:00:00+00:00",
        source: {
          source_name: "recorded_intel_sources",
          source_type: "MANAGEMENT_STATEMENT",
          source_url: "https://example.invalid/guidance",
          reliability_tier: 3,
          provenance_id: "intel-3",
        },
        provenance_id: "intel-3",
        checksum: "checksum-guidance",
      },
    ],
    counts: {
      CORPORATE_ACTION: 2,
      FINANCIAL_DISCLOSURE: 1,
      MANAGEMENT_STATEMENT: 1,
    },
    latest_at: "2026-07-30T12:00:00+00:00",
    earliest_at: "2026-06-22T18:30:00+00:00",
    notes: [],
  },
  research_status: {
    company: "TCS",
    as_of: "2026-08-10T12:00:00+00:00",
    freshness: {
      latest_published_at: "2026-07-30T12:00:00+00:00",
      latest_available_at: "2026-08-10T12:00:00+00:00",
      latest_effective_at: null,
      oldest_published_at: "2026-06-22T18:30:00+00:00",
      oldest_available_at: "2026-06-22T18:30:00+00:00",
      oldest_effective_at: null,
      days_since_latest_published: 11,
      days_since_latest_available: 0,
      stale: false,
      notes: [],
    },
    coverage: {
      item_count: 4,
      by_kind: {
        BUSINESS_EVENT: 2,
        FINANCIAL_PERIOD: 1,
        MANAGEMENT_COMMENTARY: 1,
      },
      by_category: {
        CORPORATE_ACTION: 2,
        FINANCIAL_DISCLOSURE: 1,
        MANAGEMENT_STATEMENT: 1,
      },
      by_semantic: {
        FACT: 3,
        MANAGEMENT_COMMENTARY: 1,
      },
      by_status: {
        CONFIRMED: 3,
        REPORTED: 1,
      },
      missing_categories: ["BUSINESS_NEWS", "REGULATORY_LEGAL", "OTHER"],
      notes: [
        "No evidence available for categories: BUSINESS_NEWS, REGULATORY_LEGAL, OTHER.",
      ],
    },
    quality: {
      conflict_count: 1,
      evidence_link_count: 0,
      deduplicated_count: 0,
      source_id_count: 2,
      provenance_id_count: 4,
      insufficient_evidence_notes: [],
      notes: [
        "Conflicts are surfaced as-is; the system never resolves which side is correct automatically.",
      ],
    },
  },
  rankings: {
    intraday: {
      symbol: "TCS",
      company_name: "Tata Consultancy Services",
      horizon: "INTRADAY",
      score: "61.2",
      signal: "NEUTRAL",
      confidence: "70.0",
      coverage: "100",
      missing_components: [],
      components: { momentum: "61.2" },
    },
    swing: {
      symbol: "TCS",
      company_name: "Tata Consultancy Services",
      horizon: "SWING",
      score: "63.5",
      signal: "NEUTRAL",
      confidence: "72.0",
      coverage: "100",
      missing_components: [],
      components: { momentum: "63.5" },
    },
    long_term: {
      symbol: "TCS",
      company_name: "Tata Consultancy Services",
      horizon: "LONG_TERM",
      score: "68.1",
      signal: "NEUTRAL",
      confidence: "81.1",
      coverage: "77.1",
      missing_components: ["future_readiness", "ai_participation"],
      components: { fundamentals: "77.5", risk: "90" },
    },
  },
  research_score: {
    total: "66.9",
    signal: "NEUTRAL",
    confidence: "81.1",
    components: {
      fundamentals: "77.5",
      financial_trends: "38.3",
      cash_flow: "71.7",
      balance_sheet: "100",
      risk: "90",
      management: "50",
      market_behavior: "50",
      evidence_quality: "50",
    },
  },
  deep_financial_insights: {
    symbol: "TCS",
    as_of: "2026-08-10T12:00:00+00:00",
    series: [
      {
        series_id: "TCS:ANNUAL:CONSOLIDATED",
        symbol: "TCS",
        period_type: "ANNUAL",
        consolidation: "CONSOLIDATED",
        period_count: 4,
        period_ends: [
          "2023-03-31",
          "2024-03-31",
          "2025-03-31",
          "2026-03-31",
        ],
        metrics: ["revenue", "net_profit"],
      },
    ],
    observations: [
      {
        observation_id: "TCS:2026-03-31:ANNUAL:CONSOLIDATED:revenue",
        symbol: "TCS",
        metric: "revenue",
        period_id: "TCS:2026-03-31:ANNUAL:CONSOLIDATED",
        period_end: "2026-03-31",
        period_type: "ANNUAL",
        consolidation: "CONSOLIDATED",
        observation_type: "REPORTED",
        value: "279331000000",
        previous_value: "255124000000",
        delta: "24207000000",
        delta_pct: "0.09488",
        derivation: "reported value for TCS:2026-03-31:ANNUAL:CONSOLIDATED compared against TCS:2025-03-31:ANNUAL:CONSOLIDATED",
        published_at: "2026-07-09T18:30:00+00:00",
        available_at: "2026-08-10T12:00:00+00:00",
        provenance_id: "fin-1",
      },
    ],
    comparability_notes: [],
    financial_type_counts: { REPORTED: 1 },
  },
  source_statuses: [
    {
      source_name: "recorded_intel_sources",
      source_type: "COMPANY_DISCLOSURES",
      item_count: 3,
      categories: ["MANAGEMENT_STATEMENT", "CORPORATE_ACTION"],
      latest_published_at: "2026-07-30T12:00:00+00:00",
      latest_available_at: "2026-08-10T12:00:00+00:00",
      days_since_latest_published: 11,
      stale: false,
      provenance_completeness: true,
      notes: [],
    },
  ],
  hidden_information: {
    symbol: "TCS",
    as_of: "2026-08-10T12:00:00+00:00",
    observations: [],
    notes: [],
  },
  provider_failures: [],
}

export const DEGRADED_RESEARCH: CompanyResearch = {
  ...RESEARCH,
  point_in_time: {
    ...RESEARCH.point_in_time,
    pit_checks_passed: false,
  },
  data_quality: {
    ...RESEARCH.data_quality,
    provider_failures: ["missing-sources-provider"],
    financial_data_missing: true,
  },
  provider_failures: ["missing-intel-provider"],
}
