"""
Capture recorded real-data fixtures for the multi-company
research-readiness verification milestone.

This script documents HOW the committed multi-company fixtures were
produced and regenerates the market/financial fixtures on demand.

Companies span several sectors of the Indian market:

    RELIANCE   energy / conglomerate
    INFY       information technology
    HDFCBANK   banking / financials
    SUNPHARMA  pharmaceuticals / healthcare
    M&M        automobiles

For each company:

- {ticker}_market.csv      : real daily OHLCV bars for the company
                             plus the ^NSEI benchmark, captured from
                             the Yahoo Finance market provider.
- {ticker}_financials.json : real annual financials captured from the
                             Yahoo Finance fundamentals provider.
- {ticker}_sources.json    : curated, dated public disclosures (same
                             approach as tcs_sources.json). Not
                             regenerated by this script.

The verification as-of is 2026-08-10T12:00Z. Market bars are capped
on the last completed trading day strictly before that timestamp
(2026-08-07) so the recorded data is point-in-time safe.

Usage:

    .venv/bin/python scripts/capture_multi_company_fixtures.py

Requires live network access. The generated fixtures are committed so
the pytest suite stays deterministic and offline.
"""

from __future__ import annotations

import json
import sys
from datetime import date, datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.data.providers.yahoo_financials import YahooFinanceFinancialProvider
from src.data.providers.yahoo_provider import YahooFinanceMarketDataProvider

REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_DIR = REPO_ROOT / "fixtures" / "real_data"

VERIFICATION_AS_OF = datetime(2026, 8, 10, 12, 0, tzinfo=timezone.utc)
MARKET_CUTOFF_DATE = date(2026, 8, 7)
MARKET_START_DATE = date(2025, 8, 15)
FINANCIAL_START_DATE = date(2016, 4, 1)

BENCHMARK_SYMBOL = "^NSEI"

COMPANIES = (
    "RELIANCE",
    "INFY",
    "HDFCBANK",
    "SUNPHARMA",
    "M&M",
)


def capture_market_csv(
    ticker: str,
    market_provider: YahooFinanceMarketDataProvider,
) -> Path:
    records: list[dict] = []

    for symbol in (ticker, BENCHMARK_SYMBOL):
        bars = market_provider.get_daily_prices(
            symbol,
            MARKET_START_DATE,
            MARKET_CUTOFF_DATE,
        )

        for bar in bars:
            if bar.trading_date > MARKET_CUTOFF_DATE:
                continue

            records.append(bar.model_dump(mode="json"))

    records.sort(key=lambda row: (row["symbol"], row["trading_date"]))

    target = FIXTURE_DIR / f"{ticker.lower()}_market.csv"

    with target.open("w", encoding="utf-8", newline="") as handle:
        handle.write("symbol,date,open,high,low,close,volume\n")

        for row in records:
            handle.write(
                f"{row['symbol']},{row['trading_date']},"
                f"{row['open']},{row['high']},{row['low']},"
                f"{row['close']},{row['volume']}\n"
            )

    return target


def capture_financials_json(
    ticker: str,
    financial_provider: YahooFinanceFinancialProvider,
) -> Path:
    snapshots = financial_provider.get_annual_financials(
        ticker,
        FINANCIAL_START_DATE,
        VERIFICATION_AS_OF.date(),
    )

    if not snapshots:
        raise RuntimeError(
            f"live financial capture returned no snapshots for "
            f"{ticker}. The financial fixture cannot be regenerated "
            "right now."
        )

    target = FIXTURE_DIR / f"{ticker.lower()}_financials.json"

    with target.open("w", encoding="utf-8") as handle:
        json.dump(
            {
                "captured_at": datetime.now(
                    timezone.utc
                ).isoformat(),
                "provider": "yahoo_finance_fundamentals",
                "company": ticker,
                "snapshots": [
                    snapshot.model_dump(mode="json")
                    for snapshot in snapshots
                ],
            },
            handle,
            indent=2,
            ensure_ascii=False,
        )

    return target


def main() -> None:
    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)

    market_provider = YahooFinanceMarketDataProvider(timeout=20)
    financial_provider = YahooFinanceFinancialProvider(timeout=20)

    for ticker in COMPANIES:
        market = capture_market_csv(ticker, market_provider)
        financials = capture_financials_json(ticker, financial_provider)

        print(f"wrote {market.name}")
        print(f"wrote {financials.name}")


if __name__ == "__main__":
    main()
